pim_user_user_rest_get_current:
    path: /
    defaults: { _controller: pim_user.controller.user_rest:getCurrentAction }
    requirements:
        method: GET

pim_user_user_rest_get:
    path: /{identifier}
    defaults: { _controller: pim_user.controller.user_rest:getAction }
    methods: [GET]
    requirements:

pim_user_user_rest_post:
    path: /{identifier}
    defaults: { _controller: pim_user.controller.user_rest:postAction }
    methods: [POST]
    requirements:
        identifier: '[a-zA-Z0-9_]+'
