pim_datagrid_load:
    path: /{alias}/load
    defaults: { _controller: pim_datagrid.controller.datagrid:loadAction }
    methods: ['GET']

pim_datagrid_productgrid_attributes_as_filters:
    path: /product-grid/attributes-filters
    defaults: { _controller: pim_datagrid.controller.productgrid:getAttributesAsFiltersAction }
    methods: ['GET']
