parameters:
    pim_user.controller.user_rest.class: Akeneo\UserManagement\Bundle\Controller\Rest\UserController
    pim_user.controller.security_rest.class: Akeneo\UserManagement\Bundle\Controller\Rest\SecurityController
    pim_user.controller.user_group_rest.class: Akeneo\UserManagement\Bundle\Controller\Rest\UserGroupController
    pim_user.controller.user_role_rest.class: Akeneo\UserManagement\Bundle\Controller\Rest\UserRoleController

services:
    pim_user.controller.user_rest:
        class: '%pim_user.controller.user_rest.class%'
        arguments:
            - '@security.token_storage'
            - '@pim_internal_api_serializer'
            - '@pim_user.repository.user'
            - '@pim_user.updater.user'
            - '@validator'
            - '@pim_user.saver.user'
            - '@pim_enrich.normalizer.violation'

    pim_user.controller.security_rest:
        class: '%pim_user.controller.security_rest.class%'
        arguments:
            - '@oro_security.security_facade'
            - '@oro_security.acl.annotation_provider'

    pim_user.controller.user_group_rest:
        class: '%pim_user.controller.user_group_rest.class%'
        arguments:
            - '@pim_user.repository.group'

    pim_user.controller.user_role_rest:
        class: '%pim_user.controller.user_role_rest.class%'
        arguments:
            - '@pim_user.repository.role'
            - '@serializer'
            - '@pim_user.context.user'
