parameters:
    pim_user.normalizer.user.class: Akeneo\UserManagement\Component\Normalizer\UserNormalizer

services:
    pim_user.normalizer.user:
        class: '%pim_user.normalizer.user.class%'
        arguments:
            - '@serializer.normalizer.datetime'
            - '@pim_enrich.normalizer.file'
        tags:
            - { name: pim_internal_api_serializer.normalizer }
