extensions:
    pim-user-show:
        module: pim/form/common/edit-form

    pim-user-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-user-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-system
            item: pim-menu-system-user-user

    pim-user-show-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-user-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-user-show-main-image:
        module: pim/form/common/main-image
        parent: pim-user-show
        targetZone: main-image
        config:
            fallback: '/bundles/pimui/images/info-user.png'

    pim-user-show-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-user-show
        position: 1000

    pim-user-show-label:
        module: pim/form/common/label
        parent: pim-user-show
        targetZone: title
        position: 110
        config:
            field: username

    pim-user-show-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-user-show
        targetZone: content
        position: 90

    # General tab
    pim-user-show-general-tab:
        module: pim/common/tab
        parent: pim-user-show-form-tabs
        targetZone: container
        position: 10
        config:
            label: 'General - to translate'

    pim-user-show-general-tab-content:
        module: pim/common/simple-view
        parent: pim-user-show-general-tab
        position: 10
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: ''
                dropZone: content

    pim-user-show-enabled:
        module: pim/form/common/fields/boolean
        parent: pim-user-show-general-tab-content
        position: 10
        targetZone: content
        config:
            fieldName: enabled
            label: 'Status - to translate'
            required: true
            readOnly: true

    pim-user-show-username:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 20
        targetZone: content
        config:
            fieldName: username
            label: 'Username - to translate'
            required: true
            readOnly: true

    pim-user-show-name-prefix:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 30
        targetZone: content
        config:
            fieldName: name_prefix
            label: 'Name prefix - to translate'
            readOnly: true

    pim-user-show-first-name:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 40
        targetZone: content
        config:
            fieldName: first_name
            label: 'First Name - to translate'
            required: true
            readOnly: true

    pim-user-show-middle-name:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 50
        targetZone: content
        config:
            fieldName: middle_name
            label: 'Middle Name - to translate'
            readOnly: true

    pim-user-show-last-name:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 60
        targetZone: content
        config:
            fieldName: last_name
            label: 'Last Name - to translate'
            required: true
            readOnly: true

    pim-user-show-name-suffix:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 70
        targetZone: content
        config:
            fieldName: name_suffix
            label: 'Name Suffix - to translate'
            readOnly: true

    pim-user-show-phone:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 80
        targetZone: content
        config:
            fieldName: phone
            label: 'Phone - to translate'
            readOnly: true

    pim-user-show-birthday:
        module: pim/form/common/fields/date
        parent: pim-user-show-general-tab-content
        position: 90
        targetZone: content
        config:
            fieldName: birthday
            label: 'Birthday - to translate'
            readOnly: true

    pim-user-show-avatar:
        module: pim/form/common/fields/media
        parent: pim-user-show-general-tab-content
        position: 100
        targetZone: content
        config:
            fieldName: avatar
            label: 'Avatar - to translate'
            readOnly: true

    pim-user-show-email:
        module: pim/form/common/fields/text
        parent: pim-user-show-general-tab-content
        position: 110
        targetZone: content
        config:
            fieldName: email
            label: 'Email - to translate'
            required: true
            readOnly: true

    # Additional tab
    pim-user-show-additional-tab:
        module: pim/common/tab
        parent: pim-user-show-form-tabs
        targetZone: container
        position: 20
        config:
            label: 'Additional - to translate'

    pim-user-show-additional-tab-content:
        module: pim/common/simple-view
        parent: pim-user-show-additional-tab
        position: 10
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: ''
                dropZone: content

    pim-user-show-catalog-locale:
        module: pim/form/common/fields/available-locales
        parent: pim-user-show-additional-tab-content
        position: 10
        targetZone: content
        config:
            fieldName: catalog_default_locale
            label: 'Catalog locale - to translate'
            required: true
            isMultiple: false
            allowClear: false
            readOnly: true

    pim-user-show-catalog-scope:
        module: pim/form/common/fields/scope
        parent: pim-user-show-additional-tab-content
        position: 20
        targetZone: content
        config:
            fieldName: catalog_default_scope
            label: 'Catalog scope - to translate'
            required: true
            isMultiple: false
            allowClear: false
            readOnly: true

    pim-user-show-default-tree:
        module: pim/form/common/fields/category-tree
        parent: pim-user-show-additional-tab-content
        targetZone: content
        position: 30
        config:
            fieldName: default_category_tree
            label: 'Default tree - to translate'
            required: true
            isMultiple: false
            allowClear: false
            readOnly: true

    pim-user-show-product-grid-filters:
        module: pim/form/common/fields/text
        parent: pim-user-show-additional-tab-content
        position: 40
        targetZone: content
        config:
            fieldName: productGridFilters
            label: 'Product Grid Filters - to translate'
            required: true
            readOnly: true

    # Groups and Roles tab
    pim-user-show-groups-and-roles-tab:
        module: pim/common/tab
        parent: pim-user-show-form-tabs
        targetZone: container
        position: 30
        config:
            label: 'Groups and roles - to translate'

    pim-user-show-groups-and-roles-tab-content:
        module: pim/common/simple-view
        parent: pim-user-show-groups-and-roles-tab
        position: 10
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: ''
                dropZone: content

    pim-user-show-groups:
        module: pim/form/common/fields/user-group
        parent: pim-user-show-groups-and-roles-tab-content
        targetZone: content
        position: 10
        config:
            fieldName: groups
            label: 'Groups - to translate'
            isMultiple: true
            allowClear: true
            readOnly: true

    pim-user-show-roles:
        module: pim/form/common/fields/user-role
        parent: pim-user-show-groups-and-roles-tab-content
        targetZone: content
        position: 20
        config:
            fieldName: roles
            label: 'Roles - to translate'
            isMultiple: true
            allowClear: true
            readOnly: true

    # Interfaces tab
    pim-user-show-interfaces-tab:
        module: pim/common/tab
        parent: pim-user-show-form-tabs
        targetZone: container
        position: 50
        config:
            label: 'Interfaces - to translate'

    pim-user-show-interfaces-tab-content:
        module: pim/common/simple-view
        parent: pim-user-show-interfaces-tab
        position: 10
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: ''
                dropZone: content

    pim-user-show-ui-locale:
        module: pim/form/common/fields/ui-locale
        parent: pim-user-show-interfaces-tab-content
        position: 10
        targetZone: content
        config:
            fieldName: user_default_locale
            label: 'UI Locale - to translate'
            required: true
            isMultiple: false
            allowClear: false
            readOnly: true

    pim-user-show-timezone:
        module: pim/form/common/fields/timezone
        parent: pim-user-show-interfaces-tab-content
        position: 20
        targetZone: content
        config:
            fieldName: timezone
            label: 'Timezone - to translate'
            required: true
            isMultiple: false
            allowClear: false
            readOnly: true
